config/routes.rb
Rails.application.routes.draw do

  resources :tasks do
    member do
      post 'queue'
      post 'reset'
      get 'log'
    end
  end
  resources :task_configs

  root "application#index"

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_config
  belongs_to :datum

  validates_presence_of :status, :content, :task_config

  def queue
    if datum.nil? or datum.path.nil?
      return 1
    elsif not self.status? :preparing
      return 2
    end
    data = {
      taskType:  task_config.param_hash[:task_type],
      modelType: task_config.param_hash[:model_type],
      input:     datum.path,
      output:    Rails.configuration.x.default_output_path,
      taskId:    id,
    }
    redis.publish(Rails.configuration.x.redis_key_smartscore_rpc, data.to_json)
    self.status = :queueing
    0
  end

  def status
    if valid_status?
      status = read_attribute :status
    else
      status = -1
    end
    I18n.t "task.status.#{status}"
  end

  def status= status
    if status.is_a? Symbol
      write_attribute :status, fetch_status_code(status)
    else
      write_attribute :status, status
    end
  end

  def get_status
    fetch_status_sym read_attribute :status
  end

  # Check if the task is at status [ preparing, ongoing, finished, error]
  def status? status
    read_attribute(:status) == fetch_status_code(status)
  end

  private

  def valid_status?
    status = read_attribute :status
    status.present? and [-1, 0, 1, 2, 3].find_index(status).present?
  end

  def fetch_status_code status
    case status
      when :preparing
        0
      when :queueing
        1
      when :ongoing
        2
      when :finished
        3
      when :error
        -1
      else
        -1
    end
  end

  def fetch_status_sym status
    case status
      when 0
        :preparing
      when 1
        :queueing
      when 2
        :ongoing
      when 3
        :finished
      when -1
        :error
      else
        :error
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :queue, :reset, :log]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    # update_association
    respond_to do |format|
      if @task.save
        format.html { flash[:success] = I18n.t('task.create.notice.success'); redirect_to @task }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      # update_association
      if @task.update(task_params)
        format.html { flash[:success] = I18n.t('task.update.notice.success'); redirect_to @task }

        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { flash[:danger] = I18n.t('task.destroy.notice.success'); redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  # POST /tasks/1/queue
  def queue
    ret = @task.queue
    case ret.to_i
    when 0
      flash[:info] = I18n.t('task.queue.notice.success')
    else
      flash[:danger] = I18n.t('task.queue.notice.error')
    end
    respond_to do |format|
      format.html { redirect_to tasks_url }
    end
  end

  # POST /tasks/1/reset
  def reset
    @task.status = :preparing
    @task.save!
    respond_to do |format|
      format.html { flash[:info] = I18n.t('task.reset.notice.success'); redirect_to tasks_url }
    end
  end

  # GET /tasks/1/log.json
  def log
    from = params[:from] || 0
    redis_key = "task-#{@task.id}-output"
    to = redis.llen redis_key
    log = redis.lrange redis_key, from, to

    respond_to do |format|
      format.json { render :log, locals: { from: from, to: to, log: log } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # TODO: check task_config_id & datum_id's validity.
    def task_params
      params.require(:task).permit(:content, :task_config_id, :datum_id)
    end

    def update_association
      @task.task_config = TaskConfig.find params[:task][:task_config] unless params[:task][:task_config].nil?
      @task.datum = Datum.find params[:task][:datum] unless params[:task][:datum].nil?
    end
end

app/helpers/tasks_helper.rb
module TasksHelper

  # @param task Task
  def status_label task
    case task.get_status
      when :preparing
        label_type = 'label-default'
      when :queueing
        label_type = 'label-info'
      when :ongoing
        label_type = 'label-info'
      when :finished
        label_type = 'label-success'
      when :error
        label_type = 'label-danger'
    end
    "<span class=\"label #{label_type}\">#{task.status}</span>".html_safe
  end

  # TODO: add user association.
  def get_related_task_configs
    TaskConfig.all.collect do |tc|
      [tc.name, tc.id]
    end
  end

  def get_related_data
    Datum.all.collect do |datum|
      [datum.display_name, datum.id]
    end
  end

  def link_to_task_config task
    if task.task_config.nil?
      t 'None'
    else
      link_to task.task_config.name, task_config_path(task.task_config)
    end
  end
end

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    <% if @task.errors.any? %>
      <div class="alert alert-danger alert-dismissable" id="error">
        <strong><%= t "form.error_happened" %></strong>
        <button type="button" class="close" data-dismiss="alert">x</button>

        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message.to_s %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for(@task, html: { class: 'form-horizontal' }) do |f| %>
      <fieldset>
        <legend><%= locals[:legend] %></legend>

        <div class="form-group">
          <%= f.label :content, class: 'control-label col-lg-2' %>
          <div class="col-lg-10">
            <%= f.text_area :content, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :task_config_id, class: 'control-label col-lg-2' %>
          <div class="col-lg-10">
            <%= f.select :task_config_id, get_related_task_configs, {}, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :datum_id, class: 'control-label col-lg-2' %>
          <div class="col-lg-10">
            <%= f.select :datum_id, get_related_data, {}, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= f.submit class: 'btn btn-primary' %>
            <%= link_to t('form.cancel'), :back, class: 'btn btn-default' %>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', locals: { legend: t('task.form.legend.edit') } %>

app/views/tasks/index.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th><%= t 'activerecord.attributes.task.status' %></th>
      <th><%= t 'activerecord.attributes.task.content' %></th>
      <th><%= t 'activerecord.attributes.task.task_config' %></th>
      <th><%= t 'activerecord.attributes.task.datum' %></th>
      <th colspan="4"><%= t "form.operations" %></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= status_label task %></td>
        <td><%= task.content %></td>
        <td><%= task.task_config.name %></td>
        <td><%= task.datum.try(:display_name) %></td>
        <td><%= link_to t('form.operation.show'), task %></td>
        <td><%= link_to t('form.operation.edit'), edit_task_path(task) %></td>
        <% if task.status? :finished %>
          <td><%= link_to t('form.operation.destroy'), task, method: :delete, data: { confirm: t('form.operation.destroy_confirm') } %></td>
          <td></td>
        <% elsif task.status? :preparing %>
          <td><%= link_to t('form.operation.destroy'), task, method: :delete, data: { confirm: t('form.operation.destroy_confirm') } %></td>
          <td><%= link_to t('form.operation.queue'), queue_task_path(task), method: :post %></td>
        <% elsif task.status? :error %>
          <td><%= link_to t('form.operation.destroy'), task, method: :delete, data: { confirm: t('form.operation.destroy_confirm') } %></td>
          <td><%= link_to t('form.operation.reset'), reset_task_path(task), method: :post %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('form.operation.new'), new_task_path, class: 'btn btn-block btn-success' %>

app/views/tasks/new.html.erb
<%= render 'form', locals: { legend: t('task.form.legend.new') } %>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 jumbotron">
    <p>
      <strong><%= t 'activerecord.attributes.task.id' %>: </strong>
      <span class="badge">
        <%= @task.id %>
      </span>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.task.status' %>: </strong>
      <%= status_label @task %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.task.content' %>: </strong>
      <%= @task.content %>
    </p>

    <p>
      <strong><%= t 'activerecord.attributes.task.task_config_id' %>: </strong>
      <%= link_to_task_config @task %>
    </p>

    <%- if @task.status? :preparing %>
      <%= link_to t('form.operation.edit'), edit_task_path(@task), class: 'btn btn-warning' %>
    <%- end %>
    <%= link_to t('form.back'), tasks_path, class: 'btn btn-default' %>
    <a class="btn btn-primary" href="#collapseLog" data-toggle="collapse" aria-controls="collapseLog">
      <%= t 'form.operation.show_log' %>
    </a>
  </div>
</div>
<div id="collapseLog" class="collapse"><div class="well"><pre></pre></div></div>
<%= javascript_include_tag "task_log" %>