config/routes.rb
Rails.application.routes.draw do

  resources :tasks do
    member do
      post 'queue'
      post 'reset'
      get 'log'
    end
  end
  resources :task_configs

  root "application#index"

end

app/models/task_config.rb
class TaskConfig < ActiveRecord::Base
  has_many :task

  validates_presence_of :name

  AVAILABLE_TASK_TYPE = %i(clustering classification)
  AVAILABLE_MODEL_TYPE = {
      clustering: [:canopy, :kmeans, :fuzzy_kmeans],
      classification: [:random_forest]
  }

  after_initialize do
    if @param_hash.blank?
      param_json = read_attribute :param
      if param_json.blank?
        @param_hash = {}
      else
        @param_hash = ::JSON.parse(param_json).symbolize_keys
      end
    end
  end

  validate :validate_types

  before_save do
    write_attribute :param, @param_hash.to_json
  end

  def param_hash
    if @param_hash.nil?
      @param_hash = {}
    else
      @param_hash
    end
  end

  def param_hash= param
    @param_hash = param
  end

  def task_type
    # I18n.t "task_config.task_type.#{param_hash[:task_type]}"
    param_hash[:task_type]
  end

  def task_type= type
    param_hash[:task_type] = type.to_s.to_sym
  end

  def model_type
    return '' if param_hash[:model_type].nil?
    param_hash[:model_type]
  end

  def model_type= type
    param_hash[:model_type] = type.to_sym
  end

  private
  def validate_types
    if param_hash[:task_type].blank? or param_hash[:model_type].blank?
      errors.add :base, I18n.t("activerecord.errors.models.task_config.base.task_model.blank")
    elsif not model_valid?
      errors.add :base, I18n.t("activerecord.errors.models.task_config.base.task_model.incorrect")
    end
  end

  def model_valid?
    not (
      AVAILABLE_TASK_TYPE.index(param_hash[:task_type].to_sym).nil? or
      AVAILABLE_MODEL_TYPE[param_hash[:task_type].to_sym].index(
          param_hash[:model_type].to_sym
      ).nil?
    )
  end

  def param=
  end

end

app/controllers/task_configs_controller.rb
class TaskConfigsController < ApplicationController
  before_action :set_task_config, only: [:show, :edit, :update, :destroy]

  # GET /task_configs
  # GET /task_configs.json
  def index
    @task_configs = TaskConfig.all
  end

  # GET /task_configs/1
  # GET /task_configs/1.json
  def show
  end

  # GET /task_configs/new
  def new
    @task_config = TaskConfig.new
  end

  # GET /task_configs/1/edit
  def edit
  end

  # POST /task_configs
  # POST /task_configs.json
  def create
    @task_config = TaskConfig.new(task_config_params)

    respond_to do |format|
      if @task_config.save
        format.html { flash[:success] = I18n.t('task_config.create.notice.success'); redirect_to @task_config }
        format.json { render :show, status: :created, location: @task_config }
      else
        format.html { render :new }
        format.json { render json: @task_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_configs/1
  # PATCH/PUT /task_configs/1.json
  def update
    respond_to do |format|
      if @task_config.update(task_config_params)
        format.html { flash[:success] = I18n.t('task_config.update.notice.success'); redirect_to @task_config }
        format.json { render :show, status: :ok, location: @task_config }
      else
        format.html { render :edit }
        format.json { render json: @task_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_configs/1
  # DELETE /task_configs/1.json
  def destroy
    @task_config.destroy
    respond_to do |format|
      format.html { flash[:danger] = I18n.t('task_config.destroy.notice.success'); redirect_to task_configs_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task_config
    @task_config = TaskConfig.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_config_params
    params.require(:task_config).permit(:name, :task_type, :model_type)
  end
end

app/helpers/task_configs_helper.rb
module TaskConfigsHelper

  def task_type_data task_config=nil
    TaskConfig::AVAILABLE_TASK_TYPE.map do |val|
      [t("task_config.task_type.#{val.to_s}"), val.to_s]
    end
  end

  def model_type_data task_config=nil
    if task_config.nil? or
        TaskConfig::AVAILABLE_MODEL_TYPE[@task_config.task_type.try :to_sym].nil?
      _, model = TaskConfig::AVAILABLE_MODEL_TYPE.first
    else
      model = TaskConfig::AVAILABLE_MODEL_TYPE[@task_config.task_type.to_sym]
    end
    model.map do |val|
      [t("task_config.model_type.#{val}"), val.to_s]
    end
  end

  def get_task_model_map
    ret = {}
    TaskConfig::AVAILABLE_MODEL_TYPE.each_pair  do |k, v|
      ret[k] = v.collect do |val|
        {text: t('task_config.model_type.' + val.to_s), value: val.to_s}
      end
    end
    ret
  end

end

app/views/task_configs/_form.html.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    <% if @task_config.errors.any? %>
      <div class="alert alert-danger alert-dismissable" id="error">
        <strong><%= t "form.error_happened" %></strong>
        <button type="button" class="close" data-dismiss="alert">x</button>

        <ul>
          <% @task_config.errors.full_messages.each do |message| %>
            <li><%= message.to_s %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_for(@task_config, html: { class: 'form-horizontal' }) do |f| %>
      <fieldset>
        <legend><%= locals[:legend] %></legend>

        <div class="form-group">
          <%= f.label :name, class: 'control-label col-lg-2' %>
          <div class="col-lg-10">
            <%= f.text_field :name, class: 'form-control', required: true %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :task_type, class: 'control-label col-lg-2' %>
          <div class="col-lg-10" id="model-type-select" data-select='<%= get_task_model_map.to_json %>'>
            <%= f.select :task_type, task_type_data, {}, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :model_type, class: 'control-label col-lg-2' %>
          <div class="col-lg-10">
            <%= f.select :model_type, model_type_data(@task_config), {}, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= f.submit class: 'btn btn-primary' %>
            <%= link_to t('form.cancel'), :back, class: 'btn btn-default' %>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>
<%= javascript_include_tag "task_config_form" %>

app/views/task_configs/edit.html.erb
<%= render 'form', locals: { legend: t('task_config.form.legend.edit') } %>

app/views/task_configs/index.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= t 'activerecord.attributes.task_config.name' %></th>
      <th colspan="3"><%= t "form.operations" %></th>
    </tr>
  </thead>

  <tbody>
    <% @task_configs.each do |task_config| %>
      <tr>
        <td><%= task_config.name %></td>
        <td><%= link_to t('form.operation.show'), task_config %></td>
        <td><%= link_to t('form.operation.edit'), edit_task_config_path(task_config) %></td>
        <td><%= link_to t('form.operation.destroy'), task_config, method: :delete, data: { confirm: t('form.operation.destroy_confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('form.operation.new'), new_task_config_path, class: 'btn btn-block btn-success' %>

app/views/task_configs/new.html.erb
<%= render 'form', locals: { legend: t('task_config.form.legend.new') } %>

app/views/task_configs/show.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2 jumbotron">
    <p>
      <strong><%= t 'activerecord.attributes.task_config.name' %>: </strong>
      <%= @task_config.name %>
    </p>
    <p>
      <strong><%= t 'activerecord.attributes.task_config.task_type' %>: </strong>
      <%= t 'task_config.task_type.' + @task_config.task_type %>
    </p>
    <p>
      <strong><%= t 'activerecord.attributes.task_config.model_type' %>: </strong>
      <%= t "task_config.model_type.#{@task_config.model_type}" %>
    </p>
    <%= link_to t('form.operation.edit'), edit_task_config_path(@task_config), class: 'btn btn-warning' %>
    <%= link_to t('form.back'), task_configs_path, class: 'btn btn-default' %>
  </div>
</div>